#!/usr/bin/env sh
# nav
alias path='echo $PATH | tr -s ":" "\n"'
alias mkdir="mkdir -p"
alias diff="colordiff"
alias df="df -H"
alias du="du -ch"
alias install="sudo apt-get install"
alias glog="git log --graph --oneline --decorate --date-order --color --boundary"
alias ls="ls --color=auto"
alias lh='ls -l .??*'
alias lhd='ls -ld .??*'
alias ll="ls -al"
# gzip / bzip
alias targx="tar -zxvf"
alias targc="tar -cxvf"
alias tarbx="tar --bzip2 -xvf"
alias tarbc="tar --bzip2 -cvf"
# tmux
alias tmux='tmux -2'
alias tma='tmux attach -d -t'
alias tmn='tmux new -s $(basename $(pwd))' # make -global ?
alias tml='tmux list-sessions'
# zsh
alias zshconf="vim ~/.zshrc"
alias omz="vim ~/.omz"
# R
alias R="R --no-environ --no-restore --no-save"
